from typing import Protocol, Any

class SensorReadingRepository(Protocol):
    async def find_by_period(self, start, end, variety_id=None) -> list[Any]: ...
    async def save_many(self, readings: list[dict]) -> int: ...

class MarketPriceRepository(Protocol):
    async def find_by_period(self, start, end, variety_id=None) -> list[Any]: ...

class ForecastRepository(Protocol):
    async def save_many(self, forecasts: list[dict]) -> int: ...
    async def find_latest(self, variety_id=None) -> list[Any]: ...

class SensorRepository(Protocol):
    async def find_by_code(self, code: str): ...

class GrapeVarietyRepository(Protocol):
    async def find_by_name(self, name: str): ...

class PredictiveModelRepository(Protocol):
    async def find_by_status(self, status: str) -> list[Any]: ...

class AlertRepository(Protocol):
    async def find_active(self, category=None) -> list[Any]: ...
